version: "2"
services :
  web:
    build:
      context: ./docker/apache
    env_file:
      - etc/environment.yml
    ports:
      - "80:80"
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    networks:
      main:
        aliases:
        - web
  php:
    build:
      context: ./docker/fpm
    networks:
      main:
        aliases:
          - php
    volumes:
      - ./app/:/var/www/html/

networks:
  main:
